name: Trigger Databricks Job

on:
  push:
    branches:
      - main

jobs:
  databricks-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
          
      - name: Upgrade urllib3 and chardet
        run: |
          pip install --upgrade urllib3 chardet
          
      - name: Debug Environment Variables
        run: |
          echo "Databricks Host: $DATABRICKS_HOST"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

      - name: Trigger Databricks Job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DBX_DEV_TOKEN }}
        run: |
          databricks jobs run-now --job-id 353347113846834
